name: "Package build"
on:
    pull_request:
    push:
jobs:
    home-manager-20-09:
        runs-on: ubuntu-latest
        env:
            NIXPKGS_ALLOW_UNFREE: 1
        steps:
            - uses: actions/checkout@v2.3.4
            - uses: cachix/install-nix-action@v12
              with:
                  nix_path: nixpkgs=channel:nixos-20.09:$HOME/.nix-defexpr/channels

            - run: echo $NIX_PATH

            - name: Add Home Manager
              run: nix-channel --add https://github.com/nix-community/home-manager/archive/release-20.09.tar.gz home-manager

            - name: Update channels
              run: nix-channel --update

            - run: echo $NIX_PATH

            - run: export NIX_PATH=$HOME/.nix-defexpr/channels${NIX_PATH:+:}$NIX_PATH

            - run: echo $NIX_PATH

            - run: 'cd ~; echo $PWD'

            - name: Install Home Manager
              run: nix-shell '<home-manager>' -I 'https://github.com/nix-community/home-manager/archive/release-20.09.tar.gz' -A install 