name: "Package build"
on:
    pull_request:
    push:
jobs:
    tests:
        runs-on: ubuntu-latest
        env:
            NIXPKGS_ALLOW_UNFREE: 1
        steps:
            - uses: actions/checkout@v2.3.4
            - uses: cachix/install-nix-action@v12
              with:
                  nix_path: nixpkgs=channel:nixos-20.09
            - run: nix-env -iA nixos.home-manager
